### PR TITLE
Bug fix in BannerInjection/countNumberOfEvents.py

### PR DESCRIPTION
**Pull request by scasasso**
See title

### CODE REVIEW

**Comment by alkaloge** [comment]
What is exactly the problem here ?

**Comment by scasasso** [comment]
This has been discussed with @parbol 
- The matching efficiency should be a float
- To compute the number of events needed N in order to get the desired number of events in the datasets M one should divide M by the filter efficiency rather then multiply

**Comment by scasasso** [comment]
yes, good idea, let's keep the bugs in

**Comment by alkaloge** [comment]
has been already fixed ;-) I just had problems merging your changes 
https://github.com/CMS-SUS-XPAG/GenLHEfiles/blob/master/BannerInjection/countNumberOfEvents.py

**Pull request closed without merging**
