### PR TITLE
Reorganize scripts, add LPC Condor functionality

### PR DESCRIPTION
**Pull request by kpedro88**
SUSY_generation.sh split into three parts:
* installGenerators.sh to do the initial installation of MadGraph
* setupGenEnv.(c)sh to set the MadGraph environment variables
* SUSY_generation.sh to run MadGraph

run_scan.py modified:
* uses jobExecCondor.jdl or jobExecLXbatch.sh as template files to create jobs for Condor and LXbatch, respectively
* some arguments added and functions modified to support LPC Condor

create_update_header_config.py split into two parts:
* makeMassDict.py which has the mass dictionary generation functions
* create_update_header_config.py which imports makeMassDict.py and has examples of how to use the functions and create a configuration

other things added for Condor:
* CACHEDIR.TAG in folders that store logs and output from jobs (to run on LPC Condor, the CMSSW folder is tarballed and sent to the worker node; cached directories are excluded from the tarball to reduce the file size)
* processUndecayed.sh, an example script to run Step 2 correctly with LPC EOS (using xrootd)

A separate folder "genstep" was added for the private generation step to determine the qcut values:
* the macro plotdjr.C is now located there
* sample CMSSW configuration and Condor submission scripts added to this folder

The readme file has been updated to include all of these changes. I tested the code with LXbatch using bsub (to make sure the original functionality was retained) and it appears to work. (The commit history for this branch is a little messy, but the end result is nice.)

Attn: @ferencek @nstrobbe

### CODE REVIEW

**Comment by ferencek** [comment]
@kpedro88, this PR seems to be broken in some way. I tried following the Step 1 instructions and while my Condor job was successfully created and executed, I never got my output LHE file. Do you have an idea what could be the reason?

I have a few other questions:

* why is it now necessary to run the MadGraph installation script and what is the purpose of specifying the number of cores if the `--ncores` option is not supported when running using Condor?

* the first time I ran `run_scan.py`, I was asked for my grid password. WHy is this necessary?

* the output directory parameter in `run_scan.py` does not seem to default to `lhe` but rather needs to be explicitly defined

Thanks,
Dinko

**Comment by kpedro88** [comment]
Hi Dinko,
Were you running on cmslpc, or a Tier 2/3 Condor system? I set up the code specifically for cmslpc Condor. The job executable assumes that the output LHE file should be transferred to EOS:
https://github.com/kpedro88/GenLHEfiles/blob/Condor-2/Run2Mechanism/SUSY_generation.sh#L69-71
If the output directory is not specified as an xrootd path to EOS, this will not work. This is pointed out at the very bottom of Step 1 in the readme.

* It was always necessary to run the MadGraph installation script. Previously, the installation was part of SUSY_generation.sh. I split up this script into multiple scripts, for simplification and for safety (otherwise, one could submit thousands of jobs that might *all* call wget to download and install MadGraph, which would act like a DDOS attack on the MadGraph server). It is only necessary to specify the number of cores if you want it to be different from 1. While this is not yet supported when using Condor (I think it's possible in principle, I just haven't had time to investigate), it can still be used with bsub on lxplus.
* A grid proxy is necessary to transfer files over xrootd to EOS.
* The output directory needs to be explicitly defined *for Condor* (because an xrootd EOS address must be used, as mentioned above):
https://github.com/kpedro88/GenLHEfiles/blob/Condor-2/Run2Mechanism/run_scan.py#L249-255
It can be left undefined for lxplus batch submission, and then the "lhe" default value is used.

Let me know if all of this is clear or not, and if it solves the problem you had.

-Kevin

**Comment by ferencek** [comment]
Hi, Kevin

On 06/04/2015 11:06 AM, Kevin Pedro wrote:
> Hi Dinko,
> Were you running on cmslpc, or a Tier 2/3 Condor system? I set up the
> code specifically for cmslpc Condor. The job executable assumes that the
> output LHE file should be transferred to EOS:
> https://github.com/kpedro88/GenLHEfiles/blob/Condor-2/Run2Mechanism/SUSY_generation.sh#L69-71
> If the output directory is not specified as an xrootd path to EOS, this
> will not work. This is pointed out at the very bottom of Step 1 in the
> readme.

Ah, OK, I missed that part. I think it would be better to put it earlier 
right after all run_scan.py options are listed. In general, however, I 
think it would also be useful to be able to get file copied to a local 
folder, not just EOS.

>   * It was always necessary to run the MadGraph installation script.
>     Previously, the installation was part of SUSY_generation.sh. I split
>     up this script into multiple scripts, for simplification and for
>     safety (otherwise, one could submit thousands of jobs that might
>     /all/ call wget to download and install MadGraph, which would act
>     like a DDOS attack on the MadGraph server).

I haven't looked inside SUSY_generation.sh but I agree that it is better 
to do this only once.

>     It is only necessary to
>     specify the number of cores if you want it to be different from 1.
>     While this is not yet supported when using Condor (I think it's
>     possible in principle, I just haven't had time to investigate), it
>     can still be used with bsub on lxplus.

I guess my confusion was with what happens if I specify 5 when 
installing MadGraph and then later use --ncores=8. Somehow I would 
expect this to be a runtime parameter, not an installation one.

>   * A grid proxy is necessary to transfer files over xrootd to EOS.

OK, this is clear now.

>   * The output directory needs to be explicitly defined /for Condor/
>     (because an xrootd EOS address must be used, as mentioned above):
>     https://github.com/kpedro88/GenLHEfiles/blob/Condor-2/Run2Mechanism/run_scan.py#L249-255
>     It can be left undefined for lxplus batch submission, and then the
>     "lhe" default value is used.

As I mentioned above, I think support for both EOS and the local 
filesystem would be useful.

I now tried again specifying an EOS output folder and managed to get an 
output LHE file. However, I am now facing problems with the 
update_header.py script. First, it does not seem to support ready 
directly from EOS folders. Second, when I copy the LHE files into the 
local lhe/ folder and run update_header.py, I get

[ferencek@cmslpc24 Run2Mechanism]$ python update_header.py stop2_config.cfg
Will decay according to DECAY 2000006 1.0
    1.0  2  25  1000006
DECAY 1000006 0.5
   1.0  2  6  1000022
Traceback (most recent call last):
   File "update_header.py", line 302, in <module>
     if not found_mother_mass:
NameError: name 'found_mother_mass' is not defined

The same mass dictionary defined in stop2_mass_dict.py worked just fine 
before. You can have a look at my files in 
/uscms_data/d2/ferencek/SUSY/CMSSW_7_1_12/prod/GenLHEfiles/Run2Mechanism

Thanks,
Dinko

**Comment by ferencek** [comment]
Also, the naming convention for the output LHE files seems to have changed. This now means that the updated scripts are probably no longer compatible with previously produced undecayed files. I would keep this part fully backward compatible.

**Comment by kpedro88** [comment]
Hi Dinko,

>Ah, OK, I missed that part. I think it would be better to put it earlier right after all run_scan.py options are listed. In general, however, I think it would also be useful to be able to get file copied to a local folder, not just EOS.

I moved that line in the readme so it will be more prominent.

LPC Condor worker nodes do not have permission to write directly to /uscms/home or /uscms_data. The only way to transfer Condor output to local folders is using the Condor parameters:
```
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
```
These are already turned on in the template JDL file to make sure the output, error, and log files get sent back when the job finishes.

I could add a flag in the job script to use this option for the LHE file if the "output" parameter is not set, but I would prefer not to do this. Condor automatically copies the files to the local directory from which the job was submitted, which is "scripts" in this case. (I tried to use the Condor parameter "output_destination" to redirect the output to the "lhe" directory, but had no success. I don't think this works with the LPC setup.)

>I guess my confusion was with what happens if I specify 5 when installing MadGraph and then later use --ncores=8. Somehow I would expect this to be a runtime parameter, not an installation one.

It was in the "installation" part of the old SUSY_generation.sh script, so I left it in installGenerators.sh when I reorganized things. The ncores parameter is used to configure MadGraph in some way. Maybe this configuration could be done at runtime instead of during installation, but I don't know for sure. @nstrobbe, do you know?

>However, I am now facing problems with the update_header.py script. First, it does not seem to support ready directly from EOS folders. Second, when I copy the LHE files into the local lhe/ folder and run update_header.py, I get...

This was a bug, which I have fixed.

>Also, the naming convention for the output LHE files seems to have changed. This now means that the updated scripts are probably no longer compatible with previously produced undecayed files. I would keep this part fully backward compatible.

I edited the python scripts so that the naming convention is backward-compatible.

**Comment by ferencek** [comment]
Hi Kevin,

Sorry for the delay.

On 06/19/2015 03:45 PM, Kevin Pedro wrote:
> Hi Dinko,
>
>     Ah, OK, I missed that part. I think it would be better to put it
>     earlier right after all run_scan.py options are listed. In general,
>     however, I think it would also be useful to be able to get file
>     copied to a local folder, not just EOS.
>
> I moved that line in the readme so it will be more prominent.
>
> LPC Condor worker nodes do not have permission to write directly to
> /uscms/home or /uscms_data. The only way to transfer Condor output to
> local folders is using the Condor parameters:
>
> |Should_Transfer_Files = YES
> WhenToTransferOutput = ON_EXIT
> |
>
> These are already turned on in the template JDL file to make sure the
> output, error, and log files get sent back when the job finishes.
>
> I could add a flag in the job script to use this option for the LHE file
> if the "output" parameter is not set, but I would prefer not to do this.

How about using the absolute path pointing to the logs/ subdirectory for 
the Output, Error, and Log parameters in the Condor jdl file and then 
cd-ing into the user-specified output directory and submitting jobs from 
there. That should ensure that the output LHE files end up in the 
user-specified output directory. And based on the presence or absence of 
'root://cmseos.fnal.gov/' or similar the job would determine whether it 
is supposed to copy its output to EOS or transfer it to a subdirectory 
in the users working area.

> Condor automatically copies the files to the local directory from which
> the job was submitted, which is "scripts" in this case. (I tried to use
> the Condor parameter "output_destination" to redirect the output to the
> "lhe" directory, but had no success. I don't think this works with the
> LPC setup.)
>
>     I guess my confusion was with what happens if I specify 5 when
>     installing MadGraph and then later use --ncores=8. Somehow I would
>     expect this to be a runtime parameter, not an installation one.
>
> It was in the "installation" part of the old SUSY_generation.sh script,
> so I left it in installGenerators.sh when I reorganized things. The
> ncores parameter is used to configure MadGraph in some way. Maybe this
> configuration could be done at runtime instead of during installation,
> but I don't know for sure. @nstrobbe <https://github.com/nstrobbe>, do
> you know?

Thanks for clarifying. Indeed, @nstrobbe might now the answer to this.

>     However, I am now facing problems with the update_header.py script.
>     First, it does not seem to support ready directly from EOS folders.
>     Second, when I copy the LHE files into the local lhe/ folder and run
>     update_header.py, I get...
>
> This was a bug, which I have fixed.

Hmm, this still does not work for me. When I run

python update_header.py stop2_config.cfg

with inputdir pointing to EOS I just get the following printout

Will decay according to DECAY 2000006 1.0
    1.0  2  25  1000006
DECAY 1000006 0.5
   1.0  2  6  1000022

but no files appear in lhe_processed. If I copy my undecayed LHE file 
from EOS to lhe/, and they try again

python update_header.py stop2_config.cfg

with inputdir now pointing to lhe/. I get

Will decay according to DECAY 2000006 1.0
    1.0  2  25  1000006
DECAY 1000006 0.5
   1.0  2  6  1000022
Unknown filename format, moving to the next file

So something still seems to be broken. Can you take a look at my files 
in 
/uscms_data/d2/ferencek/SUSY/CMSSW_7_1_12/prod/GenLHEfiles/Run2Mechanism 
and see what the problem is.

Btw, could CACHEDIR.TAG be renamed to .CACHEDIR.TAG so it becomes hidden?

Thanks,
Dinko

**Comment by kpedro88** [comment]
Hi Dinko,

>How about using the absolute path pointing to the logs/ subdirectory for the Output, Error, and Log parameters in the Condor jdl file and then cd-ing into the user-specified output directory and submitting jobs from there. That should ensure that the output LHE files end up in the user-specified output directory. And based on the presence or absence of 'root://cmseos.fnal.gov/' or similar the job would determine whether it is supposed to copy its output to EOS or transfer it to a subdirectory in the users working area.

I am pretty sure it is not possible to send the log files and the output LHE files to separate directories using should_transfer_files with Condor. At the least, I know that specifying the absolute path in the Output/Error/Log parameters will fail, because the worker nodes do not know about the /uscms_data area. I sent an email to cms-t1 to ask if the experts know any way around this, but I don't think there is one.

>So something still seems to be broken. Can you take a look at my files in /uscms_data/d2/ferencek/SUSY/CMSSW_7_1_12/prod/GenLHEfiles/Run2Mechanism and see what the problem is.

You were correct. I had added the mother PDG ID as a parameter used by update_header.py, but I did not add it to create_update_header_config.py. I have fixed that now, and I confirmed that your file can be processed successfully. You can look at /uscms_data/d3/pedrok/SUSY2015/test/CMSSW_7_1_12/prod/GenLHEfiles/Run2Mechanism/create_update_header_config_dinko.py to see how I made the config to process your file.

>Btw, could CACHEDIR.TAG be renamed to .CACHEDIR.TAG so it becomes hidden?

No, this file must be named exactly as it is: see [http://www.brynosaurus.com/cachedir/spec.html](http://www.brynosaurus.com/cachedir/spec.html).

**Comment by ferencek** [comment]
Hi Kevin,

On 06/23/2015 04:38 PM, Kevin Pedro wrote:
> Hi Dinko,
>
>     How about using the absolute path pointing to the logs/ subdirectory
>     for the Output, Error, and Log parameters in the Condor jdl file and
>     then cd-ing into the user-specified output directory and submitting
>     jobs from there. That should ensure that the output LHE files end up
>     in the user-specified output directory. And based on the presence or
>     absence of 'root://cmseos.fnal.gov/' or similar the job would
>     determine whether it is supposed to copy its output to EOS or
>     transfer it to a subdirectory in the users working area.
>
> I am pretty sure it is not possible to send the log files and the output
> LHE files to separate directories using should_transfer_files with
> Condor. At the least, I know that specifying the absolute path in the
> Output/Error/Log parameters will fail, because the worker nodes do not
> know about the /uscms_data area. I sent an email to cms-t1 to ask if the
> experts know any way around this, but I don't think there is one.

The following simple jdl file

universe = vanilla
Executable = /bin/sleep
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Output = /uscms_data/d2/ferencek/BTV/sleep_$(Cluster)_$(Process).stdout
Error = /uscms_data/d2/ferencek/BTV/sleep_$(Cluster)_$(Process).stderr
Log = /uscms_data/d2/ferencek/BTV/sleep_$(Cluster)_$(Process).log
Arguments = 20
Queue 5

works for me so I think that using absolute paths will work for the log 
files in your case as well.

>     So something still seems to be broken. Can you take a look at my
>     files in
>     /uscms_data/d2/ferencek/SUSY/CMSSW_7_1_12/prod/GenLHEfiles/Run2Mechanism
>     and see what the problem is.
>
> You were correct. I had added the mother PDG ID as a parameter used by
> update_header.py, but I did not add it to
> create_update_header_config.py. I have fixed that now, and I confirmed
> that your file can be processed successfully. You can look at
> /uscms_data/d3/pedrok/SUSY2015/test/CMSSW_7_1_12/prod/GenLHEfiles/Run2Mechanism/create_update_header_config_dinko.py
> to see how I made the config to process your file.

Great. It works now. But as I said before, it seems that using input 
directories on EOS using paths that start with 
root://cmseos.fnal.gov//store/ does not work. A possible workaround is 
to use a path that starts with /eos/uscms/store/. So I think this is one 
more reason to be able to get the undecayed LHE files directly to the 
local file system.

>     Btw, could CACHEDIR.TAG be renamed to .CACHEDIR.TAG so it becomes
>     hidden?
>
> No, this file must be named exactly as it is: see
> http://www.brynosaurus.com/cachedir/spec.html.

Thanks. TLDR ;)

Cheers,
Dinko

**Comment by kpedro88** [comment]
>works for me so I think that using absolute paths will work for the log files in your case as well.

I'm surprised that that worked. I must have an incomplete understanding of what Condor can access. Anyway, I implemented the local output option the way you described, and it appears to work fine.

**Comment by ferencek** [comment]
OK, getting files locally now works as well. However, I noticed that even when I store files locally, I'm asked for my GRID password. Could this be disabled when not using EOS?

I also tried the whole setup on Condor at T3 at Rutgers but it did not completely work. The test Condor job I submitted seemed to work just fine with condor log saying
```
000 (53962.000.000) 06/24 14:35:51 Job submitted from host: <192.168.1.109:9434>
...
001 (53962.000.000) 06/24 14:36:14 Job executing on host: <192.168.1.62:9174>
...
006 (53962.000.000) 06/24 14:36:22 Image size of job updated: 2
	3  -  MemoryUsage of job (MB)
	2164  -  ResidentSetSize of job (KB)
...
006 (53962.000.000) 06/24 14:41:22 Image size of job updated: 277220
	98  -  MemoryUsage of job (MB)
	100272  -  ResidentSetSize of job (KB)
...
005 (53962.000.000) 06/24 14:47:16 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:05:40, Sys 0 00:00:00  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:05:40, Sys 0 00:00:00  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	42730  -  Run Bytes Sent By Job
	26104910  -  Run Bytes Received By Job
	42730  -  Total Bytes Sent By Job
	26104910  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated
	   Cpus                 :                 1         1
	   Disk (KB)            :   227094  1000000   1767426
	   Memory (MB)          :       98      199      4029
...
```
but there was no output file shipped to the `lhe/` subdirectory. I also see
```
/HTClocal/execute/dir_19714/condor_exec.exe: line 26: scram: command not found
```
in the stderr file. However, I won't waste time further investigating since it is possible that something is not configured correctly with the Condor installation.

Something I still don't quite understand is the need for CACHEDIR.TAG files. In the main version of the package, everything can be checked even out outside the CMSSW tree (I would even argue that should be a requirement). Also, why is there a need to tar the whole CMSSW tree. How is that used later? Would it be easier to do something like
```bash
export SCRAM_ARCH=slc6_amd64_gcc481
source /cvmfs/cms.cern.ch/cmsset_default.sh
cmsrel CMSSW_7_1_12
cd CMSSW_7_1_12
eval `scramv1 runtime -sh`
```
on the worker node itself in order to get the CMSSW environment set up, etc. There should be no need for these CACHEDIR.TAG files which I or somebody else will inevitably delete by mistake at some point. Also, people might store their output in a subdirectory other than `lhe/` and tar will be then packaging those subdirectories as well.

**Comment by kpedro88** [comment]
> OK, getting files locally now works as well. However, I noticed that even when I store files locally, I'm asked for my GRID password. Could this be disabled when not using EOS?

Fixed.

> I also tried the whole setup on Condor at T3 at Rutgers but it did not completely work.

I make no guarantees about out-of-the-box functionality at T2/T3 clusters ;). It's even noted in the readme:
>You might need to make changes here and there to get it to run on the local T2 (e.g. for batch submission). 
Each T2/T3 cluster has its own specific environment and Condor settings. I wrote the scripts specifically for the LPC Condor configuration. (As a Fermilab postdoc, I only have access to the LPC for testing things.) I think it is not feasible to achieve a fully general setup that will work with any Condor configuration. Users can fork the repository and make changes for their home cluster if they want.

```
/HTClocal/execute/dir_19714/condor_exec.exe: line 26: scram: command not found
```

This might occur if the Rutgers T3 does not use CVMFS to manage its CMSSW installations. (Just one example of the many site-dependent settings that must be understood for batch submission scripts...)

>Something I still don't quite understand is the need for CACHEDIR.TAG files. In the main version of the package, everything can be checked even outside the CMSSW tree (I would even argue that should be a requirement). Also, why is there a need to tar the whole CMSSW tree. How is that used later?

The example you show is acceptable if the user is running a standard CMSSW config that does not rely on any private code. That is not the case here: this entire repository (plus the installed generator directory) is necessary to run the production. If we were to use your example, the job script would have to run `git clone` and `./installGenerators.sh` (which includes several `wget` calls) for every single job in order to get the necessary code. That can quickly become a nightmare scenario for batch submission, when thousands of jobs might be sending requests over the web simultaneously. Transmitting the code in a tarball over the local network is a more stable and general solution (and typically the jobs will run faster, also).

>There should be no need for these CACHEDIR.TAG files which I or somebody else will inevitably delete by mistake at some point. Also, people might store their output in a subdirectory other than lhe/ and tar will be then packaging those subdirectories as well.

I added a paragraph about the CACHEDIR.TAG file to the README so the user will understand when to add it to a custom output directory. There's only so much hand-holding that we can do.

As far as future accidental deletion of the files: if you want LPC Condor functionality, this is the best way I know how to do it. I don't know what else to tell you.

**Comment by ferencek** [comment]
Hi Kevin,

On 06/26/2015 12:51 PM, Kevin Pedro wrote:
>     OK, getting files locally now works as well. However, I noticed that
>     even when I store files locally, I'm asked for my GRID password.
>     Could this be disabled when not using EOS?
>
> Fixed.

Thanks.

>     I also tried the whole setup on Condor at T3 at Rutgers but it did
>     not completely work.
>
> I make no guarantees about out-of-the-box functionality at T2/T3
> clusters ;). It's even noted in the readme:
>
>     You might need to make changes here and there to get it to run on
>     the local T2 (e.g. for batch submission).
>     Each T2/T3 cluster has its own specific environment and Condor
>     settings. I wrote the scripts specifically for the LPC Condor
>     configuration. (As a Fermilab postdoc, I only have access to the LPC
>     for testing things.) I think it is not feasible to achieve a fully
>     general setup that will work with any Condor configuration. Users
>     can fork the repository and make changes for their home cluster if
>     they want.

Yes, I was aware of this and I agree, each site can have a different 
Condor configuration so it's hard to have something general.

> |/HTClocal/execute/dir_19714/condor_exec.exe: line 26: scram: command not found
> |
>
> This might occur if the Rutgers T3 does not use CVMFS to manage its
> CMSSW installations. (Just one example of the many site-dependent
> settings that must be understood for batch submission scripts...)

It uses CVMFS but it's is entirely possible that it does not handle the 
file transfer in the same way FNAL does (I remember from some other use 
cases that it worked fine if one would write the output files directly 
to his/her output directory while transferring at the end did not work 
properly).

>     Something I still don't quite understand is the need for
>     CACHEDIR.TAG files. In the main version of the package, everything
>     can be checked even outside the CMSSW tree (I would even argue that
>     should be a requirement). Also, why is there a need to tar the whole
>     CMSSW tree. How is that used later?
>
> The example you show is acceptable if the user is running a standard
> CMSSW config that does not rely on any private code. That is not the
> case here: this entire repository (plus the installed generator
> directory) is necessary to run the production. If we were to use your
> example, the job script would have to run |git clone| and
> |./installGenerators.sh| (which includes several |wget| calls) for every
> single job in order to get the necessary code. That can quickly become a
> nightmare scenario for batch submission, when thousands of jobs might be
> sending requests over the web simultaneously. Transmitting the code in a
> tarball over the local network is a more stable and general solution
> (and typically the jobs will run faster, also).

Thanks for reminding me about each job using wget, etc. So with your 
version even if one runs using lxbatch at CERN, this type of excessive 
downloading is not performed and instead each job ships a tarball with it?

>     There should be no need for these CACHEDIR.TAG files which I or
>     somebody else will inevitably delete by mistake at some point. Also,
>     people might store their output in a subdirectory other than lhe/
>     and tar will be then packaging those subdirectories as well.
>
> I added a paragraph about the CACHEDIR.TAG file to the README so the
> user will understand when to add it to a custom output directory.
> There's only so much hand-holding that we can do.

I agree, there must be some limit. I was just wondering if there is a 
more robust way to exclude directories. Instead of having multiple 
CACHEDIR.TAG files, wouldn't it be better to simply use the tar 
`--exclude=` option. One could even include the user-defined output 
directory in the exclude list if it is different from the default `lhe/` 
directory.

@alkaloge, @nstrobbe, what do you think about merging this PR?

Best,
Dinko

**Comment by nstrobbe** [comment]
Merged. Keep up the good work :-)

**Comment by kpedro88** [comment]
Thanks!

@ferencek:

>Thanks for reminding me about each job using wget, etc. So with your version even if one runs using lxbatch at CERN, this type of excessive downloading is not performed and instead each job ships a tarball with it?

The lxbatch system has read/write permissions for user home directories, so in that case the code is just accessed directly from where the user installs it.

>I agree, there must be some limit. I was just wondering if there is a more robust way to exclude directories. Instead of having multiple CACHEDIR.TAG files, wouldn't it be better to simply use the tar `--exclude=` option. One could even include the user-defined output directory in the exclude list if it is different from the default `lhe/` directory.

Personally, I find it easier to add CACHEDIR.TAG files to directories that I want to exclude, instead of having an ever-growing `-exclude=` option. (I tried this a while ago and it was harder to maintain.) I actually have an alias command to do this quickly, which I got from @drberry85:
```
alias cachedir 'echo "Signature: 8a477f597d28d172789f06886806bc55\n# This file is a cache directory tag.\n# For information about cache directory tags, see:\n#       http://www.brynosaurus.com/cachedir/" > CACHEDIR.TAG'
```
Let me know if you want me to try the solution that I added to my previous comment as an edit, in which `run_scan.py` would automatically generate the CACHEDIR.TAG files for the relevant directories instead of tracking those files in the repo.

**Comment by ferencek** [comment]
Sorry, I missed the edit. Yes, I like the proposed solution where `run_scan.py` behaves as before and produces the required directories and automatically puts the CACHEDIR.TAG file inside each of them.

**Pull request merged**
